### PR TITLE
automake -> cmake

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
This allows windows users to take advantage of cmake for compilation. vcpkg can still be used as an option.

As for actually allowing the compilation to run on windows, we have to decide how to handle the `add_subdirectory(foo)` bug that ninja has.

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
This is now passes all existing checks  bergamot-translator, except the windows compilation.

**Comment by XapaJIaMnu** [comment]
This now also allows compilation on ubuntu 16.04

**Comment by XapaJIaMnu** [comment]
Any idea why tests fail? They work locally...?

**Comment by jerinphilip** [comment]
@XapaJIaMnu not a directory output change given you changed the relative path? You'll have to edit the workflows to point to new location of executable?

**Comment by XapaJIaMnu** [comment]
On my manual Linux build, the output file location doesn't change.

**Comment by XapaJIaMnu** [comment]
@ugermann all tests pass, compiles cleanly on win32, mac, linux, can use internal and external pcre2 and works even on older ubuntu like 16.04.

**Comment by ugermann** [comment]
Superseded by #19

**Pull request closed without merging**
