### PR TITLE
Windows build fixes and workflow

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
Added windows build fixes and a workflow... Not sure how to run the workflow

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
@ugermann I added a windows workflow, but not sure how to add it to the actions, could you help?

**Comment by ugermann** [comment]
Excellent, I'd been looking into this, too, but got distracted by trying to sort out an earlier pull request by Jerin. Looks good. I'm glad you figured out the vcpkg route for getting prce2.

**Comment by XapaJIaMnu** [comment]
I got this to compile on my Windows environment, but I didn't manage to test the work flow (I couldn't trigger it to run). Did you manage to run it?

**Comment by ugermann** [comment]
Got it to run but it's currently failing. I suspect an issue with the vcpkg setup. I'm looking into this right now.

**Comment by XapaJIaMnu** [comment]
I don't think so. I saw something similar on the internet, and I think it's a bug with Ninja: https://github.com/raspberrypi/pico-sdk/issues/11

**Comment by XapaJIaMnu** [comment]
Ok, I'm able to reproduce this on my windows, but i have no idea what's happening

**Comment by ugermann** [comment]
Do avoid divergence, I've integrated and just pushed what I approve of in #14.

**Pull request merged**
